workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    environment:
      # NO configurar ios_signing - el IPA se genera sin firmar
      # Para firmarlo después, usa Sideloadly o configura certificados en Settings
      # Si quieres firma automática, configura certificados en Settings → Code signing
      # y luego descomenta la sección ios_signing abajo
      
      # ios_signing:
      #   distribution_type: ad_hoc
      #   bundle_identifier: com.ios.nequixofficialv2
      
      vars:
        XCODE_WORKSPACE: "iosApp/NequixiOS.xcworkspace"
        XCODE_SCHEME: "NequixiOS"
        XCODE_PROJECT: "iosApp/NequixiOS.xcodeproj"
        
      cocoapods: default
      
    scripts:
      - name: Fix Xcode Signing (CRITICAL - FIRST STEP)
        script: |
          chmod +x ./fix_xcode_signing.sh || true
          ./fix_xcode_signing.sh || echo "Warning: Could not fix signing"
          
      - name: Prepare iOS Build
        script: |
          chmod +x ./gradlew
          chmod +x ./prepare_ios_build.sh || true
          
      - name: Build Shared Framework
        script: |
          echo "🔨 Compilando framework compartido para iOS..."
          # Compilar para todas las arquitecturas iOS
          ./gradlew :shared:compileKotlinIosArm64 :shared:compileKotlinIosX64 :shared:compileKotlinIosSimulatorArm64 || echo "Warning: Some iOS targets may not compile"
          
          # Generar el framework para CocoaPods
          ./gradlew :shared:podInstall || {
            echo "Error en podInstall, intentando generar framework manualmente..."
            ./gradlew :shared:linkPodReleaseFrameworkIosArm64 :shared:linkPodReleaseFrameworkIosX64 || true
          }
          
          # Verificar que el framework existe
          if [ -d "shared/build/cocoapods/framework/shared.framework" ]; then
            echo "✅ Framework compartido compilado correctamente"
            FRAMEWORK_SIZE=$(du -sh shared/build/cocoapods/framework/shared.framework | cut -f1)
            echo "📊 Tamaño del framework: $FRAMEWORK_SIZE"
            ls -lh shared/build/cocoapods/framework/shared.framework/
            
            # Verificar que el framework tenga el binario
            if [ -f "shared/build/cocoapods/framework/shared.framework/shared" ]; then
              BINARY_SIZE=$(du -h shared/build/cocoapods/framework/shared.framework/shared | cut -f1)
              echo "✅ Binario del framework encontrado - Tamaño: $BINARY_SIZE"
            else
              echo "⚠️ ADVERTENCIA: No se encontró el binario del framework"
            fi
          else
            echo "⚠️ Framework no encontrado en ubicación esperada"
            find shared/build -name "shared.framework" -type d || echo "No se encontró framework"
          fi
          
      - name: Install CocoaPods Dependencies
        script: |
          cd iosApp
          echo "📦 Instalando dependencias de CocoaPods..."
          pod install --repo-update
          echo "✅ CocoaPods instalado"
          
          # Dar permisos de ejecución a todos los scripts de CocoaPods
          echo "🔧 Dando permisos de ejecución a scripts de CocoaPods..."
          find "Pods/Target Support Files" -name "*.sh" -type f -exec chmod +x {} \; || true
          
          # Corregir el script de CocoaPods para evitar error de variable no definida
          FRAMEWORKS_SCRIPT="Pods/Target Support Files/Pods-NequixiOS/Pods-NequixiOS-frameworks.sh"
          if [ -f "$FRAMEWORKS_SCRIPT" ]; then
            echo "🔧 Corrigiendo script de CocoaPods..."
            chmod +x "$FRAMEWORKS_SCRIPT"
            # Agregar verificación de variables antes de usar source
            sed -i '' 's/source "$SCRIPT_INPUT_FILE_0"/[ -f "$SCRIPT_INPUT_FILE_0" ] \&\& source "$SCRIPT_INPUT_FILE_0"/g' "$FRAMEWORKS_SCRIPT" || \
            sed -i 's/source "$SCRIPT_INPUT_FILE_0"/[ -f "$SCRIPT_INPUT_FILE_0" ] \&\& source "$SCRIPT_INPUT_FILE_0"/g' "$FRAMEWORKS_SCRIPT" || true
            # Deshabilitar modo estricto en el script - usar echo en lugar de sed con newline
            echo -e "set +u\n$(cat $FRAMEWORKS_SCRIPT)" > "$FRAMEWORKS_SCRIPT.tmp" && mv "$FRAMEWORKS_SCRIPT.tmp" "$FRAMEWORKS_SCRIPT" || true
            chmod +x "$FRAMEWORKS_SCRIPT"
            echo "✅ Script corregido y con permisos"
          fi
          cd ..
          
      - name: Pre-build shared framework for CocoaPods
        script: |
          echo "🔨 Pre-compilando framework para evitar error en script phase..."
          # Pre-compilar el framework para que CocoaPods no intente compilarlo durante el build
          export OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED=YES
          ./gradlew :shared:syncFramework \
            -Pkotlin.native.cocoapods.platform=iphoneos \
            -Pkotlin.native.cocoapods.archs="arm64" \
            -Pkotlin.native.cocoapods.configuration=Release || echo "Warning: syncFramework puede fallar, continuando..."
          
      - name: Disable automatic signing in Xcode project
        script: |
          # Modificar el proyecto para deshabilitar signing
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$XCODE_PROJECT/project.pbxproj" || \
          sed -i 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$XCODE_PROJECT/project.pbxproj" || true
          sed -i '' 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' "$XCODE_PROJECT/project.pbxproj" || \
          sed -i 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' "$XCODE_PROJECT/project.pbxproj" || true
          
      - name: Build IPA without signing
        script: |
          set +e  # No salir inmediatamente en errores
          set +u  # No tratar variables no definidas como error
          mkdir -p build/ios/ipa
          
          # Deshabilitar el script phase de CocoaPods que está fallando
          export OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED=YES
          
          # Configurar variables para el script de CocoaPods
          export STRIP_INSTALLED_PRODUCT=YES
          export EMBEDDED_CONTENT_CONTAINS_SWIFT=YES
          export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=YES
          
          echo "🔍 Verificando workspace y scheme..."
          ls -la "$XCODE_WORKSPACE" || echo "Workspace no encontrado"
          xcodebuild -list -workspace "$XCODE_WORKSPACE" || echo "Error listando workspace"
          
          echo "📦 Compilando archive..."
          # Intentar build con diferentes opciones
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/archive.xcarchive \
            -destination "generic/platform=iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="" \
            PROVISIONING_PROFILE="" \
            DEVELOPMENT_TEAM="" \
            OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED=YES \
            archive 2>&1 | tee build.log || {
            echo "❌ Error en archive, intentando build directo..."
            # Intentar build sin archive
            xcodebuild -workspace "$XCODE_WORKSPACE" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -destination "generic/platform=iOS" \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              build
            # Buscar el .app compilado
            APP_PATH=$(find build -name "*.app" -type d | head -1)
            if [ -n "$APP_PATH" ]; then
              echo "✅ App encontrada en: $APP_PATH"
              mkdir -p build/ios/ipa/Payload
              cp -R "$APP_PATH" build/ios/ipa/Payload/
              cd build/ios/ipa
              zip -r ../NequixiOS.ipa Payload
              cd ../../..
              echo "✅ IPA creado desde build directo"
              exit 0
            fi
            echo "❌ Error completo del build"
            cat build.log || true
            exit 1
          }
          
          echo "📦 Verificando archive creado..."
          if [ -d "build/archive.xcarchive/Products/Applications" ]; then
            APP_NAME=$(ls build/archive.xcarchive/Products/Applications/ | head -1)
            APP_PATH="build/archive.xcarchive/Products/Applications/$APP_NAME"
            echo "✅ App encontrada: $APP_NAME"
            
            # Verificar tamaño del .app (debe ser al menos varios MB)
            APP_SIZE=$(du -sm "$APP_PATH" | cut -f1)
            echo "📊 Tamaño del .app: ${APP_SIZE}MB"
            
            if [ "$APP_SIZE" -lt 1 ]; then
              echo "⚠️ ADVERTENCIA: El .app es muy pequeño (${APP_SIZE}MB). Verificando contenido..."
              echo "Contenido del .app:"
              ls -lh "$APP_PATH" || true
              echo "Frameworks:"
              ls -lh "$APP_PATH/Frameworks" 2>/dev/null || echo "⚠️ No se encontró carpeta Frameworks"
              echo "Recursos:"
              ls -lh "$APP_PATH"/*.plist 2>/dev/null || echo "⚠️ No se encontraron plists"
            fi
            
            # Verificar que el shared framework esté incluido
            if [ -d "$APP_PATH/Frameworks/shared.framework" ]; then
              echo "✅ Framework compartido encontrado"
              ls -lh "$APP_PATH/Frameworks/shared.framework" | head -5
            else
              echo "⚠️ ADVERTENCIA: Framework compartido NO encontrado en Frameworks/"
              find "$APP_PATH" -name "shared.framework" -type d || echo "No se encontró shared.framework en ningún lugar"
            fi
            
            mkdir -p build/ios/ipa/Payload
            cp -R "$APP_PATH" build/ios/ipa/Payload/
            cd build/ios/ipa
            zip -r ../NequixiOS.ipa Payload
            cd ../../..
            IPA_PATH="build/ios/ipa/NequixiOS.ipa"
            echo "✅ IPA creado: $IPA_PATH"
            # Verificar que el IPA existe
            if [ -f "$IPA_PATH" ]; then
              IPA_SIZE=$(du -h "$IPA_PATH" | cut -f1)
              IPA_SIZE_MB=$(du -sm "$IPA_PATH" | cut -f1)
              ls -lh "$IPA_PATH"
              echo "✅ IPA verificado correctamente - Tamaño: ${IPA_SIZE} (${IPA_SIZE_MB}MB)"
              
              if [ "$IPA_SIZE_MB" -lt 5 ]; then
                echo "⚠️ ADVERTENCIA: El IPA es muy pequeño (${IPA_SIZE_MB}MB). Puede faltar contenido."
                echo "Verificando contenido del IPA..."
                unzip -l "$IPA_PATH" | head -30
              fi
            else
              echo "⚠️ IPA no encontrado en $IPA_PATH, buscando..."
              FOUND_IPA=$(find build -name "*.ipa" -type f | head -1)
              if [ -n "$FOUND_IPA" ]; then
                echo "✅ IPA encontrado en: $FOUND_IPA"
                ls -lh "$FOUND_IPA"
                # Copiar al lugar esperado
                mkdir -p build/ios/ipa
                cp "$FOUND_IPA" "$IPA_PATH"
                echo "✅ IPA copiado a ubicación esperada"
              else
                echo "❌ No se encontró ningún IPA"
                exit 1
              fi
            fi
          else
            echo "❌ No se encontró la aplicación en el archive"
            echo "Contenido de archive:"
            ls -la build/archive.xcarchive/ || true
            ls -la build/archive.xcarchive/Products/ || true
            exit 1
          fi
            
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/NequixiOS.ipa
      
    publishing:
      email:
        recipients:
          - tu-email@gmail.com
        notify:
          success: true
          failure: true

