workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    environment:
      flutter: none
      
      vars:
        XCODE_WORKSPACE: "iosApp/NequixiOS.xcworkspace"
        XCODE_SCHEME: "NequixiOS"
        XCODE_PROJECT: "iosApp/NequixiOS.xcodeproj"
        
      xcode: 15.0
      cocoapods: default
      
    scripts:
      - name: Prepare iOS Build
        script: |
          chmod +x ./gradlew
          chmod +x ./prepare_ios_build.sh || true
          
      - name: Build Shared Framework
        script: |
          ./gradlew :shared:podInstall
          
      - name: Install CocoaPods Dependencies
        script: |
          cd iosApp
          pod install --repo-update
          
      - name: Disable automatic signing in Xcode project
        script: |
          # Modificar el proyecto para deshabilitar signing
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$XCODE_PROJECT/project.pbxproj" || \
          sed -i 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$XCODE_PROJECT/project.pbxproj" || true
          sed -i '' 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' "$XCODE_PROJECT/project.pbxproj" || \
          sed -i 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' "$XCODE_PROJECT/project.pbxproj" || true
          
      - name: Build IPA without signing
        script: |
          mkdir -p build/ios/ipa
          
          # Deshabilitar signing completamente
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/archive.xcarchive \
            -destination "generic/platform=iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="" \
            PROVISIONING_PROFILE="" \
            DEVELOPMENT_TEAM="" \
            archive || exit 1
          
          # Crear IPA manualmente desde el archive
          if [ -d "build/archive.xcarchive/Products/Applications" ]; then
            APP_NAME=$(ls build/archive.xcarchive/Products/Applications/ | head -1)
            mkdir -p build/ios/ipa/Payload
            cp -R "build/archive.xcarchive/Products/Applications/$APP_NAME" build/ios/ipa/Payload/
            cd build/ios/ipa
            zip -r ../NequixiOS.ipa Payload
            cd ../../..
            echo "✅ IPA creado: build/ios/ipa/NequixiOS.ipa"
            ls -lh build/ios/ipa/*.ipa
          else
            echo "❌ No se encontró la aplicación en el archive"
            exit 1
          fi
            
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      email:
        recipients:
          - tu-email@gmail.com
        notify:
          success: true
          failure: true

