workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    environment:
      # NO configurar ios_signing para evitar detección automática
      # NO configurar flutter - este proyecto no usa Flutter
      
      vars:
        XCODE_WORKSPACE: "iosApp/NequixiOS.xcworkspace"
        XCODE_SCHEME: "NequixiOS"
        XCODE_PROJECT: "iosApp/NequixiOS.xcodeproj"
        
      cocoapods: default
      
    scripts:
      - name: Fix Xcode Signing (CRITICAL - FIRST STEP)
        script: |
          chmod +x ./fix_xcode_signing.sh || true
          ./fix_xcode_signing.sh || echo "Warning: Could not fix signing"
          
      - name: Prepare iOS Build
        script: |
          chmod +x ./gradlew
          chmod +x ./prepare_ios_build.sh || true
          
      - name: Build Shared Framework
        script: |
          echo "🔨 Compilando framework compartido para iOS..."
          # Compilar para todas las arquitecturas iOS
          ./gradlew :shared:compileKotlinIosArm64 :shared:compileKotlinIosX64 :shared:compileKotlinIosSimulatorArm64 || echo "Warning: Some iOS targets may not compile"
          
          # Generar el framework para CocoaPods
          ./gradlew :shared:podInstall || {
            echo "Error en podInstall, intentando generar framework manualmente..."
            ./gradlew :shared:linkPodReleaseFrameworkIosArm64 :shared:linkPodReleaseFrameworkIosX64 || true
          }
          
          # Verificar que el framework existe
          if [ -d "shared/build/cocoapods/framework/shared.framework" ]; then
            echo "✅ Framework compartido compilado correctamente"
            ls -lh shared/build/cocoapods/framework/shared.framework/
          else
            echo "⚠️ Framework no encontrado en ubicación esperada"
            find shared/build -name "shared.framework" -type d || echo "No se encontró framework"
          fi
          
      - name: Install CocoaPods Dependencies
        script: |
          cd iosApp
          echo "📦 Instalando dependencias de CocoaPods..."
          pod install --repo-update
          echo "✅ CocoaPods instalado"
          
          # Dar permisos de ejecución a todos los scripts de CocoaPods
          echo "🔧 Dando permisos de ejecución a scripts de CocoaPods..."
          find "Pods/Target Support Files" -name "*.sh" -type f -exec chmod +x {} \; || true
          
          # Corregir el script de CocoaPods para evitar error de variable no definida
          FRAMEWORKS_SCRIPT="Pods/Target Support Files/Pods-NequixiOS/Pods-NequixiOS-frameworks.sh"
          if [ -f "$FRAMEWORKS_SCRIPT" ]; then
            echo "🔧 Corrigiendo script de CocoaPods..."
            chmod +x "$FRAMEWORKS_SCRIPT"
            # Agregar verificación de variables antes de usar source
            sed -i '' 's/source "$SCRIPT_INPUT_FILE_0"/[ -f "$SCRIPT_INPUT_FILE_0" ] \&\& source "$SCRIPT_INPUT_FILE_0"/g' "$FRAMEWORKS_SCRIPT" || \
            sed -i 's/source "$SCRIPT_INPUT_FILE_0"/[ -f "$SCRIPT_INPUT_FILE_0" ] \&\& source "$SCRIPT_INPUT_FILE_0"/g' "$FRAMEWORKS_SCRIPT" || true
            # Deshabilitar modo estricto en el script - usar echo en lugar de sed con newline
            echo -e "set +u\n$(cat $FRAMEWORKS_SCRIPT)" > "$FRAMEWORKS_SCRIPT.tmp" && mv "$FRAMEWORKS_SCRIPT.tmp" "$FRAMEWORKS_SCRIPT" || true
            chmod +x "$FRAMEWORKS_SCRIPT"
            echo "✅ Script corregido y con permisos"
          fi
          cd ..
          
      - name: Pre-build shared framework for CocoaPods
        script: |
          echo "🔨 Pre-compilando framework para evitar error en script phase..."
          # Pre-compilar el framework para que CocoaPods no intente compilarlo durante el build
          export OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED=YES
          ./gradlew :shared:syncFramework \
            -Pkotlin.native.cocoapods.platform=iphoneos \
            -Pkotlin.native.cocoapods.archs="arm64" \
            -Pkotlin.native.cocoapods.configuration=Release || echo "Warning: syncFramework puede fallar, continuando..."
          
      - name: Disable automatic signing in Xcode project
        script: |
          # Modificar el proyecto para deshabilitar signing
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$XCODE_PROJECT/project.pbxproj" || \
          sed -i 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$XCODE_PROJECT/project.pbxproj" || true
          sed -i '' 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' "$XCODE_PROJECT/project.pbxproj" || \
          sed -i 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' "$XCODE_PROJECT/project.pbxproj" || true
          
      - name: Build IPA without signing
        script: |
          set +e  # No salir inmediatamente en errores
          set +u  # No tratar variables no definidas como error
          mkdir -p build/ios/ipa
          
          # Deshabilitar el script phase de CocoaPods que está fallando
          export OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED=YES
          
          # Configurar variables para el script de CocoaPods
          export STRIP_INSTALLED_PRODUCT=YES
          export EMBEDDED_CONTENT_CONTAINS_SWIFT=YES
          export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=YES
          
          echo "🔍 Verificando workspace y scheme..."
          ls -la "$XCODE_WORKSPACE" || echo "Workspace no encontrado"
          xcodebuild -list -workspace "$XCODE_WORKSPACE" || echo "Error listando workspace"
          
          echo "📦 Compilando archive..."
          # Intentar build con diferentes opciones
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/archive.xcarchive \
            -destination "generic/platform=iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="" \
            PROVISIONING_PROFILE="" \
            DEVELOPMENT_TEAM="" \
            OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED=YES \
            archive 2>&1 | tee build.log || {
            echo "❌ Error en archive, intentando build directo..."
            # Intentar build sin archive
            xcodebuild -workspace "$XCODE_WORKSPACE" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -destination "generic/platform=iOS" \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              build
            # Buscar el .app compilado
            APP_PATH=$(find build -name "*.app" -type d | head -1)
            if [ -n "$APP_PATH" ]; then
              echo "✅ App encontrada en: $APP_PATH"
              mkdir -p build/ios/ipa/Payload
              cp -R "$APP_PATH" build/ios/ipa/Payload/
              cd build/ios/ipa
              zip -r ../NequixiOS.ipa Payload
              cd ../../..
              echo "✅ IPA creado desde build directo"
              exit 0
            fi
            echo "❌ Error completo del build"
            cat build.log || true
            exit 1
          }
          
          echo "📦 Verificando archive creado..."
          if [ -d "build/archive.xcarchive/Products/Applications" ]; then
            APP_NAME=$(ls build/archive.xcarchive/Products/Applications/ | head -1)
            echo "✅ App encontrada: $APP_NAME"
            mkdir -p build/ios/ipa/Payload
            cp -R "build/archive.xcarchive/Products/Applications/$APP_NAME" build/ios/ipa/Payload/
            cd build/ios/ipa
            zip -r ../NequixiOS.ipa Payload
            cd ../../..
            echo "✅ IPA creado: build/ios/ipa/NequixiOS.ipa"
            ls -lh build/ios/ipa/*.ipa
          else
            echo "❌ No se encontró la aplicación en el archive"
            echo "Contenido de archive:"
            ls -la build/archive.xcarchive/ || true
            ls -la build/archive.xcarchive/Products/ || true
            exit 1
          fi
            
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      email:
        recipients:
          - tu-email@gmail.com
        notify:
          success: true
          failure: true

