workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.ios.nequixofficialv2
      flutter: none
      
      vars:
        XCODE_WORKSPACE: "iosApp/NequixiOS.xcworkspace"
        XCODE_SCHEME: "NequixiOS"
        XCODE_PROJECT: "iosApp/NequixiOS.xcodeproj"
        
      xcode: 15.0
      cocoapods: default
      groups:
        - codemagic
        
    scripts:
      - name: Prepare iOS Build
        script: |
          chmod +x ./gradlew
          chmod +x ./prepare_ios_build.sh || true
          
      - name: Build Shared Framework
        script: |
          ./gradlew :shared:podInstall
          
      - name: Install CocoaPods Dependencies
        script: |
          cd iosApp
          pod install --repo-update
          
      - name: Set up code signing
        script: |
          keychain initialize
          
      - name: Build IPA
        script: |
          mkdir -p build/ios/ipa
          
          # Intentar build normal primero
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/archive.xcarchive \
            -destination "generic/platform=iOS" \
            archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO || \
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/archive.xcarchive \
            -destination "generic/platform=iOS" \
            archive
          
          # Exportar IPA
          if [ -d "build/archive.xcarchive" ]; then
            xcodebuild -exportArchive \
              -archivePath build/archive.xcarchive \
              -exportPath build/ios/ipa \
              -exportOptionsPlist iosApp/ExportOptions.plist || \
            (mkdir -p build/ios/ipa/Payload && \
             cp -R build/archive.xcarchive/Products/Applications/*.app build/ios/ipa/Payload/ && \
             cd build/ios/ipa && zip -r ../NequixiOS.ipa Payload && cd ../..)
          fi
            
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      email:
        recipients:
          - tu-email@gmail.com
        notify:
          success: true
          failure: true
