workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR
          pod install --repo-update
      - name: Build iOS
        script: |
          cd $CM_BUILD_DIR
          xcodebuild -workspace NequixiOS.xcworkspace \
            -scheme NequixiOS \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -archivePath build/NequixiOS.xcarchive \
            archive
      - name: Create IPA
        script: |
          cd $CM_BUILD_DIR
          mkdir -p build/Payload
          cp -r build/NequixiOS.xcarchive/Products/Applications/NequixiOS.app build/Payload/
          cd build
          zip -r NequixiOS.ipa Payload
    artifacts:
      - build/*.ipa
      - build/NequixiOS.xcarchive
