platform :ios, '15.0'

target 'NequixiOS' do
  use_frameworks!

  pod 'Firebase/Auth', '~> 10.25.0'
  pod 'Firebase/Firestore', '~> 10.25.0'
  pod 'Firebase/Storage', '~> 10.25.0'
  pod 'Firebase/Messaging', '~> 10.25.0'
  pod 'Firebase/Analytics', '~> 10.25.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
